_core_/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("demo.urls")),
]

account/urls.py
"""account/urls.py"""

from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("", views.AccountListView.as_view(), name="list"),
    path("<int:pk>/", views.AccountDetailView.as_view(), name="detail"),
    path("create/", views.AccountCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.AccountUpdateView.as_view(), name="update"),
    path("self-update/", views.AccountSelfUpdateView.as_view(), name="selfupdate"),
    path("login/", views.AccountLoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("captcha-challange/", views.captcha_challange, name="captcha_challange"),
]

demo/urls.py
from django.urls import path
from .views import demo_view

urlpatterns = [
    path("", demo_view, name="demo"),
]

zorg/urls.py
from django.urls import path

zorg/models.py
# zorg/models.py
from django.conf import settings
from django.db import models
from simple_history.models import HistoricalRecords
from zorg.middleware import get_current_user


class AuditModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="%(class)s_created",
        editable=False,
    )
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="%(class)s_modified",
        editable=False,
    )

    history = HistoricalRecords(inherit=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        user = get_current_user()
        if not self.pk and not self.created_by:
            self.created_by = user
        else:
            self.modified_by = user
        super().save(*args, **kwargs)

zorg/views.py
from django.shortcuts import render

zorg/templates/zorg/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "zorg/header.html" %}
    <title>
      {{ APP_SHORT_NAME }}
      {% block browser_title %}
      {% endblock browser_title %}
    </title>
    {% block page_style %}
    {% endblock page_style %}
  </head>
  <body>
    <div class="bws-main-wrapper">
      {% include "zorg/top_nav.html" %}
      {% include "zorg/side_nav.html" %}
      <div class="bws-content-wrapper">
        <main>
          <div class="container-fluid px-4">
            {% block page_header %}
            {% endblock page_header %}
            {% include "zorg/flash_alert.html" %}
            {% block page_content %}
            {% endblock page_content %}
          </div>
        </main>
        {% include "zorg/footer.html" %}
      </div>
    </div>
    <script src='{% static "js/bootstrap.bundle.min.js" %}'> </script>
    <script src='{% static "js/use-bootstrap-select.min.js" %}'></script>
    <script src='{% static "js/script.js" %}'></script>
    {% block page_script %}
    {% endblock page_script %}
  </body>
</html>

zorg/templates/zorg/flash_alert.html
{% if messages %}
    <div class="row">
        <div class="col">
            {% for message in messages %}
                <div class="alert alert-dismissible fade show {% if message.tags %}{{ message.tags }}{% endif %}"
                     role="alert">
                    {{ message }}
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="alert"
                            aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

zorg/templates/zorg/footer.html
<footer class="mt-auto">
  <div class="container-fluid py-2 px-4 bg-light mt-3">
    <div class="d-flex align-items-center justify-content-center small">
      <div class="text-muted">
        {{ COPYRIGHT_SHORT_TEXT }} {% now 'Y' %}
      </div>
    </div>
  </div>
</footer>

zorg/templates/zorg/header.html
{% load static %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="{{ APP_DESCRIPTION }}" />
<meta name="keywords" content="{{ APP_KEYWORDS }}" />
<meta name="author" content="{{ APP_AUTHOR }}" />
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}" />
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}" />
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}" />
<link rel="stylesheet" href="{% static 'css/styles.css' %}" />

zorg/templates/zorg/side_nav.html
{% load custom_tags %}

<div class="bws-side-nav-wrapper">
  <nav class="bws-sidenav accordion bws-sidenav-dark" id="side-nav-root">
    <div class="bws-sidenav-menu">
      <div class="nav">{% include "side_nav_urls.html" %}</div>
    </div>
    <div class="bws-sidenav-footer">
      {% if user.is_authenticated %}
        <div class="small">Logged in as:</div>
        {{ user.username }}
      {% else %}
        <div class="text-center">
          <a class="btn btn-sm btn-outline-primary" href="{% url 'account:login' %}" title="Sign In">Sign In</a>
        </div>
      {% endif %}
    </div>
  </nav>
</div>

zorg/templates/zorg/top_nav.html
<nav class="bws-top-nav-wrapper navbar navbar-expand navbar-dark bg-primary">
  <!-- Navbar Brand-->
  <span class="navbar-brand ps-3">{{ APP_SHORT_NAME }}</span>
  <!-- Sidebar Toggle-->
  <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!">
    <i class="bi bi-list h3"></i>
  </button>
  <!-- Navbar-->
  <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
    {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown"
           href="#"
           role="button"
           data-bs-toggle="dropdown"
           aria-expanded="false">
          <i class="bi bi-person-lines-fill h5"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <li>
            <a class="dropdown-item" href='{% url "account:selfupdate" %}'>Account</a>
          </li>
          <li>
            <hr class="dropdown-divider" />
          </li>
          <li>
            {% if user.is_authenticated %}
              <form method="post" action="{% url 'account:logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-link dropdown-item">Logout</button>
              </form>
            {% else %}
              <a class="dropdown-item" href="{% url 'account:login' %}">Log in</a>
            {% endif %}
          </li>
        </ul>
      </li>
    {% endif %}
  </ul>
</nav>